### ISSUE TITLE
"No options defined for block variation"

### ISSUE THREAD

**Issue by RobMcDesign** [underscoretype/fontsampler-js#38]
I'm trying to get a variable axis, I've followed the example from 
[https://underscoretype.github.io/fontsampler-js/variable.html](https://underscoretype.github.io/fontsampler-js/variable.html)

I've added the axes and instances to the font var
name: "VariableFontName",
    files: ["VariableFontFile.woff2"],
    axes: ["wght"],
    instances: [
         "wght 500, | VariableFontName Regular",]

I've added a variation element
order: ["tester", ["fontsize", "variation", "fontfamily"]],

and I've tried to define that element
variation: {
    axes: [{
        tag: "wght",
        init: 400,
        min: 250,
        max: 900,
        step: 10,
        label: "Weight"
    }]
},

but I'm still getting the error. Am I missing something? I couldn't find any more documentation on variable font support.

**Comment by kontur** [comment]
The API has now changed quite a bit, and the documentation shows the correct way to define variable font instances.
