### ISSUE TITLE
Some UI options don't work?

### ISSUE THREAD

**Issue by nedkamburov** [underscoretype/fontsampler-js#39]
Hello there, I have been implementing this library with relative ease and joy but I have hit a roadblock. 

This is my options config for the fontsampler:

```
{
      order: [["fontfamily", "language", "fontsize", "alignment", "opentype"], "tester"],
      ui: {
        tester: {
          editable: false,
          label: false,
        },

        language: {
          choices: ["enGB|English", "deDe|Deutsch", "nlNL|Dutch"],
          init: "enGb",
          label: false,
        },

        opentype: {
          choices: ["liga|Ligatures", "frac|Fractions"],
          init: ["liga"],
          label: "Opentype features",
        },
      },
      lazyload: true,
    }
```

The `order`, `language ui choices` and `lazyload` work however any options for the `tester` or the `label` field on any feature doesn't do anything... 

@kontur Am I using the wrong data structure or I am missing something? Thanks a lot!

**Comment by nedkamburov** [comment]
I think I found the culprit, the field should be called `config`, not `ui`... There definitely should be an update of the docs.
```
config: {
        tester: {
          editable: false,
          label: false,
        }
}
```

**Comment by kontur** [comment]
> There definitely should be an update of the docs.

Oh yes, I must have missed that rename in the docs, my bad! Feel free to send a PR with the text corrected in the docs.

**Comment by nedkamburov** [comment]
I forked the project to take a look and it seems like the [online version](https://underscoretype.github.io/fontsampler-js/) is a little different. 

I cannot seem to find the source anywhere in the codebase. Is it possible that the static version is using an old version of `index.html`? @kontur

**Comment by kontur** [comment]
Finally had a look at these and fixed some things that were off with the documentation 👍
