### ISSUE TITLE
(dumb)Question: how would I go about installing this into a Webflow project?

### ISSUE THREAD

**Issue by Kron98** [underscoretype/fontsampler-js#6]
Installed npm in my PC but have no idea on how to make it usable in my Webflow project. CDN is an option, I think :S

**Comment by Kron98** [comment]
Managed to learn how :)

**Comment by kontur** [comment]
Hey,
I'm not overly familiar with webflow or its limitations, but if you can upload or add your own JS and CSS files you can load the files from the `dist` folder. I don't maintain any CDN distribution of this package, but that or any other hosting of the `dist` folder files would be an option indeed.

Hope this late comment helps in any way ;)

**Comment by Kron98** [comment]
> Hey,
> I'm not overly familiar with webflow or its limitations, but if you can upload or add your own JS and CSS files you can load the files from the `dist` folder. I don't maintain any CDN distribution of this package, but that or any other hosting of the `dist` folder files would be an option indeed.
> 
> Hope this late comment helps in any way ;)

Thank you! I actually just sent you an email regarding that with a longer explanation of what I am doing :)
